### PR TITLE
Feature ny articles - Code Review

### PR DESCRIPTION
**Pull request by rsnazario**
This is the first submitting of the Project "New York Article",  from Rafael Nazario and Josue Abraham. //

We applied the requests for the html and most of the requests for the css.
CSS: It keeps asking to move one selector before others, but they were not related in our opinion.

### CODE REVIEW

**Review by fatymahmed — CHANGES_REQUESTED** [review]
## Hi @techbabouche @rsnazario,
Great job on the project, I like how descriptive the README file is, however, there are a couple of things that you need to change.

- [ ]  The footer should have a fixed position (it sticks to the bottom part of the screen)

- [ ] You seem to have some HTML errors, Check HTML markup with this validator https://validator.w3.org/#validate_by_upload. 
validation_requirement
( screenshot from Pathwright)

- [ ] You should use `<aside>` tag for Editor's picks section on the righmost side. 
aside_requirement
(screenshot from Pathwright) 

- The 'Sign up for Science Times' section  and the 'Editors pick' on the rightmost seem to be overlapping with the main content, kindly fix this, see screenshot below.

Screenshot from 2019-12-10 21-19-56

- Your footer isn't aligned with the main content,see the screenshot below and please also fix this.

Screenshot from 2019-12-10 21-20-49

- kindly fix the stickler errors
### Kindly make changes and request for another code review.

## Status : Changes required
_Feel free to reach out to me on slack (fatima) if you have any questions._

**Comment by rsnazario** [comment]
Completed the requests. We choose to did not apply all the changes of the stickler because it did not make sense for us

**Comment by Anna-Myzukina** [comment]
#### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi team!
### Wow! The project looks really very good! The readme file is so descriptive! :+1:  

- Kindly recommended fix footer as told previous code review.
 Your footer isn't aligned with the main content, please see the screenshot below


footer

The property margin-left: 350px; makes these changes in your footer.
Please check this peace of code and try to fix that situation.
.related-content {
    max-width: 95%;
    margin-left: 350px;
}

- Please remember that commits should be descriptive. I hope in future projects you can do it! screenshot 
You can read more about it here [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)

### Make changes and submit another code review request.


*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
Happy coding

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
The project still needs changes in footer

**Comment by rsnazario** [comment]
Please check the e-mail I just sent you!

**Comment by rsnazario** [comment]
Hello, 

Josue and I are struggling to correct the last part of the project, so we feel like we really need your help because we tried everything we could.

It has been happening a few problems. The more complicated and "non-sense" stuff is this: 

https://mail.google.com/mail/u/0?ui=2&ik=af85bad75e&attid=0.1&permmsgid=msg-a:r-7440833060819492185&th=16ef5db18504480b&view=fimg&sz=s0-l75-ft&attbid=ANGjdJ_i9PCEnpDmiIJgO3xxPmtE6kqIs7V6btm343Zst-n2oKPTUkz-5BC7lQJuRptUpcsHR4ZUY3foVyIoHwW-izrC22uHWH-2v8uhtFc6Z3wdArSnKSb8R-bzziw&disp=emb&realattid=ii_k41ilq380

When we don't set as "Display: inline-block" it just expands the box to a huge model, but we are not setting any of the sizes for it, nor width or height.

After solving that this problem would "disappear" once we added the display:inline-block (it would just set a box to the size of the elements, just as is should happen as default) 
Following the correct standards, we would just apply "margin: 0 auto;" or even "margin: auto;" 
To both commands, we get this result:

https://mail.google.com/mail/u/0?ui=2&ik=af85bad75e&attid=0.2&permmsgid=msg-a:r-7440833060819492185&th=16ef5db18504480b&view=fimg&sz=s0-l75-ft&attbid=ANGjdJ9HHZTitxtLBK5kSqmvc2971MUryluwG8aIv6X1bhxlnMJf0kt_h3FUBVhfW_3ohYcWR98Hxhqs0aVhrLse6ED61slgK6e_0A_QoVBRvErwevSOGNnUAsoOSLg&disp=emb&realattid=ii_k41ir0sr1

At this point, we have corrected the size of the box, but the margin auto is not working HERE ( It does work through all the other elements that we applied correctly).
Then, we start "playing" around with the values for margin... when we set as 15% margin-left, in my screen it fits nicely, but not at Josue's.
Also, if I zoom in, the related content moves up to the right, and when I zoom out, it moves to the left. 

Josue works with two screens, and he has the same problem. It looks one thing at one screen, but totally different on the other.

We worked on this section mostly with %, so, why is that? 

All the other sections that we worked with pixels instead and margin:auto are working fine, but the footer is showing these problems.

We really don't know anything else we could do. The only thing in mind would be to go over all the css again and change it all to % instead of pixels or rem's, but we are not sure that this will correct our problem.

I hope you can help us. 

Rafael Nazario and Josue Abraham.

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Hello team! :rocket:
Really great job so far and thank you for bringing up the challenge you're facing. I just requested a re-review, however please don't submit it yet, I am currently writing a few suggestions I will share shortly as to how you may fix your issue. When you go through and make required changes, you may submit for another review :+1: 

#### Stay tuned!  :smile:

**Comment by rsnazario** [comment]
Josue my partner figured it out. 

We have a different habits of working so he changed the styling to use the same units in our whole css file.

**Comment by shshamim63** [comment]
## Status :taco: :tada: !! Approved !! :tada: :taco: 
___
Hi @rsnazario  & @techbabouche :wave: ,
You guys have done a great job :clap: . Code looks neat and clean. Well descriptive readme with a short description on PR. In one word __Tremendous__ . 
___
#### This :+1: is from me. you can merge it and don't forget to fill the project completion form.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](Shakhawat Hossain)

**Pull request merged**
